# Generated by Django 3.2.6 on 2021-09-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgshare', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=10000),
        ),
    ]
