# Generated by Django 3.2.6 on 2021-09-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgshare', '0003_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
