# Generated by Django 3.2.6 on 2021-09-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgshare', '0004_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='followers',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='following',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
